-- MySQL Script generated by MySQL Workbench
-- ter 18 set 2018 16:29:36 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` INT(20) NOT NULL,
  `rg` INT(20) NOT NULL,
  `dataNascimentoPessoa` DATE NOT NULL,
  `sexoPessoa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(200) NULL,
  `ruaEnderecoPessoa` VARCHAR(45) NULL,
  `numeroEnderecoPessoa` VARCHAR(45) NULL,
  `bairroEnderecoPessoa` VARCHAR(45) NULL,
  `cidadeEnderecoPessoa` VARCHAR(45) NULL,
  `estadoEnderecoPessoa` VARCHAR(45) NULL,
  `paisEnderecoPessoa` VARCHAR(45) NULL,
  `cepEnderecoPessoa` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` INT(20) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idTelefone`, `Pessoa_idPessoa`),
  UNIQUE INDEX `idTelefone_UNIQUE` (`idTelefone` ASC) VISIBLE,
  INDEX `fk_Telefone_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `tipoCliente(crianca,adolescente,adulto,idoso)` VARCHAR(45) NOT NULL,
  `Pessoas_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Pessoas_idPessoa`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Clientes_Pessoas1_idx` (`Pessoas_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `tipoVendedor(interno, externo)` VARCHAR(45) NOT NULL,
  `Pessoas_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idVendedor`, `Pessoas_idPessoa`),
  UNIQUE INDEX `idVendedor_UNIQUE` (`idVendedor` ASC) VISIBLE,
  INDEX `fk_Vendedores_Pessoas1_idx` (`Pessoas_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Vendedores_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Barco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Barco` (
  `idBarco` INT NOT NULL AUTO_INCREMENT,
  `nomeBarco` VARCHAR(45) NOT NULL,
  `cnpjBarco` INT NOT NULL,
  `lotacaoBarco` INT NOT NULL,
  `proprietarioBarco` VARCHAR(45) NOT NULL,
  `comandanteBarco` VARCHAR(45) NOT NULL,
  `tipoBarco` VARCHAR(45) NULL,
  `ruaEnderecoBarco` VARCHAR(45) NULL,
  `numeroEnderecoBarco` INT NULL,
  `bairroEnderecoBarco` VARCHAR(45) NULL,
  `cidadeEnderecoBarco` VARCHAR(45) NULL,
  `estadoEnderecoBarco` VARCHAR(45) NULL,
  `paisEnderecoBarco` VARCHAR(45) NULL,
  `cepEnderecoBarco` VARCHAR(45) NULL,
  PRIMARY KEY (`idBarco`),
  UNIQUE INDEX `idBarco_UNIQUE` (`idBarco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passagem` (
  `idPassagem` INT UNSIGNED NOT NULL,
  `statusPassagem` VARCHAR(45) NOT NULL,
  `Barco_idBarco` INT NOT NULL,
  PRIMARY KEY (`idPassagem`, `Barco_idBarco`),
  UNIQUE INDEX `idPassagem_UNIQUE` (`idPassagem` ASC) VISIBLE,
  INDEX `fk_Passagem_Barco1_idx` (`Barco_idBarco` ASC) VISIBLE,
  CONSTRAINT `fk_Passagem_Barco1`
    FOREIGN KEY (`Barco_idBarco`)
    REFERENCES `mydb`.`Barco` (`idBarco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `valorVenda` FLOAT NOT NULL,
  `descontoVenda` FLOAT NOT NULL,
  `formaPagamentoVenda` VARCHAR(45) NOT NULL,
  `dataHoraVenda` DATE NOT NULL,
  `qrcodePassagem` BLOB NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Passagem_idPassagem` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Vendedor_idVendedor`, `Cliente_idCliente`, `Passagem_idPassagem`),
  UNIQUE INDEX `idVenda_UNIQUE` (`idVenda` ASC) VISIBLE,
  INDEX `fk_Vendas_Vendedores1_idx` (`Vendedor_idVendedor` ASC) VISIBLE,
  INDEX `fk_Vendas_Clientes1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Vendas_Passagens1_idx` (`Passagem_idPassagem` ASC) VISIBLE,
  UNIQUE INDEX `Vendedor_idVendedor_UNIQUE` (`Vendedor_idVendedor` ASC) VISIBLE,
  UNIQUE INDEX `Clientes_idCliente_UNIQUE` (`Cliente_idCliente` ASC) VISIBLE,
  UNIQUE INDEX `Passagens_idPassagem_UNIQUE` (`Passagem_idPassagem` ASC) VISIBLE,
  UNIQUE INDEX `qrcodePassagem_UNIQUE` (`qrcodePassagem` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_Vendedores1`
    FOREIGN KEY (`Vendedor_idVendedor`)
    REFERENCES `mydb`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Clientes1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Passagens1`
    FOREIGN KEY (`Passagem_idPassagem`)
    REFERENCES `mydb`.`Passagem` (`idPassagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `descricaoCidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idCidade`),
  UNIQUE INDEX `idCidade_UNIQUE` (`idCidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rota` (
  `idRota` INT NOT NULL AUTO_INCREMENT,
  `descricaoRota` VARCHAR(45) NOT NULL,
  `cidadeOrigemRota` INT NOT NULL,
  `cidadeDestinoRota` INT NOT NULL,
  PRIMARY KEY (`idRota`, `cidadeOrigemRota`, `cidadeDestinoRota`),
  UNIQUE INDEX `idRota_UNIQUE` (`idRota` ASC) VISIBLE,
  INDEX `fk_Rota_Cidade1_idx` (`cidadeOrigemRota` ASC) VISIBLE,
  INDEX `fk_Rota_Cidade2_idx` (`cidadeDestinoRota` ASC) VISIBLE,
  CONSTRAINT `fk_Rota_Cidade1`
    FOREIGN KEY (`cidadeOrigemRota`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rota_Cidade2`
    FOREIGN KEY (`cidadeDestinoRota`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nomePerfil` VARCHAR(45) NOT NULL,
  `descricaoPerfil` VARCHAR(200) NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC) VISIBLE,
  UNIQUE INDEX `nomePerfil_UNIQUE` (`nomePerfil` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(45) NOT NULL,
  `dataCriacaoUsuario` DATE NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Pessoa_idPessoa`, `Perfil_idPerfil`),
  UNIQUE INDEX `idLogin_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `usuarioLogin_UNIQUE` (`nomeUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Usuario_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viagem` (
  `idViagem` INT NOT NULL AUTO_INCREMENT,
  `dataPartidaViagem` DATE NOT NULL,
  `dataChegadaViagem` DATE NOT NULL,
  `valorTransporteViagem` FLOAT NOT NULL,
  `valorAlimentacaoViagem` FLOAT NOT NULL,
  `dataInicioViagem` DATE NOT NULL,
  `dataTerminoViagem` DATE NOT NULL,
  `Barco_idBarco` INT NOT NULL,
  `Rota_idRota` INT NOT NULL,
  PRIMARY KEY (`idViagem`, `Barco_idBarco`, `Rota_idRota`),
  UNIQUE INDEX `idViagem_UNIQUE` (`idViagem` ASC) VISIBLE,
  INDEX `fk_Viagem_Barco1_idx` (`Barco_idBarco` ASC) VISIBLE,
  INDEX `fk_Viagem_Rota1_idx` (`Rota_idRota` ASC) VISIBLE,
  CONSTRAINT `fk_Viagem_Barco1`
    FOREIGN KEY (`Barco_idBarco`)
    REFERENCES `mydb`.`Barco` (`idBarco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Rota1`
    FOREIGN KEY (`Rota_idRota`)
    REFERENCES `mydb`.`Rota` (`idRota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acomodacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acomodacao` (
  `idAcomodacao` INT NOT NULL AUTO_INCREMENT,
  `nomeAcomodacao` VARCHAR(45) NOT NULL,
  `descricaoAcomodacao` VARCHAR(45) NULL,
  `quantidadeAcomodacao` INT NOT NULL,
  `capacidadeAcomodacao` INT NOT NULL,
  `Barco_idBarco` INT NOT NULL,
  PRIMARY KEY (`idAcomodacao`),
  UNIQUE INDEX `idAcomodacao_UNIQUE` (`idAcomodacao` ASC) VISIBLE,
  INDEX `fk_Acomodacao_Barco1_idx` (`Barco_idBarco` ASC) VISIBLE,
  CONSTRAINT `fk_Acomodacao_Barco1`
    FOREIGN KEY (`Barco_idBarco`)
    REFERENCES `mydb`.`Barco` (`idBarco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
